server:
  port: 8085

spring:
  application:
    name: gamebox-record
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gamebox_record?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
